[package]
name = "jj-gpc"
version = "0.4.0"
edition = "2021"
license-file = "LICENSE.md"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
ollama-rs = "0.2.1"
regex = "1.11.1"
tokio = { version = "1.41.1", features = ["macros", "rt"] }
